# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- script: dotnet tool install --global dotnet-ef
  displayName: 'Install Entity Framework tooling'
- script: dotnet ef database update --project "$(Build.SourcesDirectory)/Tidbeat/Tidbeat.csproj"
  displayName: 'Update database'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(de444514-4044-4ec2-be34-817d4be2042a)'
    appType: 'webAppLinux'
    appName: 'Tidbeat2'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
